### ISSUE TITLE
srad.fut parse error

### ISSUE THREAD

**Issue by LaurentPlagne** [HIPERFIT/futhark-ppopp17#1]
Hi,
make command in futhark-pldi directory produces the following message:
`futhark-opencl futhark-benchmarks/rodinia/srad/srad.fut`
`Parse error at futhark-benchmarks/rodinia/srad/srad.fut:53:28-53:28`
`If you find this error message confusing, uninformative, or wrong, please open an issue at https://github.com/HIPERFIT/futhark/issues.`

Any ideas ?

Thank you for your help

Laurent

**Comment by athas** [comment]
Yes, sorry about that.  We tweaked the syntax of the `loop` construct in Futhark yesterday.  The solution is either:

1. Install a newer Futhark compiler (the one currently on Git will work, as will the newest nightly build).

2. Delete the `futhark-benchmarks` directory from your checkout of `futhark-pldi17` and let the Makefile re-create it from the newest version on Git.

Doing both will also work.

You can also manually clone exactly the Futhark and `futhark-benchmarks` revisions used for the paper (Git hashes are in the README), but there is probably no reason to do that.
